/**
 * Platform-wide constants for Zentra
 */

// Account statuses
export const ACCOUNT_STATUS = {
    ACTIVE: 'ACTIVE',
    SUSPENDED: 'SUSPENDED',
    DELETED: 'DELETED',
};

export const ACCOUNT_STATUS_VALUES = Object.values(ACCOUNT_STATUS);

// Seller statuses
export const SELLER_STATUS = {
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    SUSPENDED: 'SUSPENDED',
    REJECTED: 'REJECTED',
};

export const SELLER_STATUS_VALUES = Object.values(SELLER_STATUS);

// Store statuses
export const STORE_STATUS = {
    ACTIVE: 'ACTIVE',
    SUSPENDED: 'SUSPENDED',
    CLOSED: 'CLOSED',
};

export const STORE_STATUS_VALUES = Object.values(STORE_STATUS);

// Product statuses
export const PRODUCT_STATUS = {
    DRAFT: 'DRAFT',
    PUBLISHED: 'PUBLISHED',
    ARCHIVED: 'ARCHIVED',
};

export const PRODUCT_STATUS_VALUES = Object.values(PRODUCT_STATUS);

// Payment statuses
export const PAYMENT_STATUS = {
    INITIATED: 'INITIATED',
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED',
    REFUNDED: 'REFUNDED',
};

export const PAYMENT_STATUS_VALUES = Object.values(PAYMENT_STATUS);

// Verification statuses
export const VERIFICATION_STATUS = {
    PENDING: 'PENDING',
    UNDER_REVIEW: 'UNDER_REVIEW',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
};

export const VERIFICATION_STATUS_VALUES = Object.values(VERIFICATION_STATUS);

// Document types for seller verification
export const DOCUMENT_TYPE = {
    GOVT_ID: 'GOVT_ID',
    BUSINESS_REGISTRATION: 'BUSINESS_REGISTRATION',
    TAX_DOCUMENT: 'TAX_DOCUMENT',
    ADDRESS_PROOF: 'ADDRESS_PROOF',
    BANK_STATEMENT: 'BANK_STATEMENT',
};

export const DOCUMENT_TYPE_VALUES = Object.values(DOCUMENT_TYPE);

// Business types
export const BUSINESS_TYPE = {
    INDIVIDUAL: 'INDIVIDUAL',
    SOLE_PROPRIETOR: 'SOLE_PROPRIETOR',
    COMPANY: 'COMPANY',
};

export const BUSINESS_TYPE_VALUES = Object.values(BUSINESS_TYPE);

// Address types
export const ADDRESS_TYPE = {
    SHIPPING: 'SHIPPING',
    BILLING: 'BILLING',
};

export const ADDRESS_TYPE_VALUES = Object.values(ADDRESS_TYPE);

// Address labels
export const ADDRESS_LABEL = {
    HOME: 'HOME',
    WORK: 'WORK',
    OTHER: 'OTHER',
};

export const ADDRESS_LABEL_VALUES = Object.values(ADDRESS_LABEL);

// Gender options
export const GENDER = {
    MALE: 'MALE',
    FEMALE: 'FEMALE',
    OTHER: 'OTHER',
    UNSPECIFIED: 'UNSPECIFIED',
};

export const GENDER_VALUES = Object.values(GENDER);

// Auth providers
export const AUTH_PROVIDER = {
    LOCAL: 'LOCAL',
};

export const AUTH_PROVIDER_VALUES = Object.values(AUTH_PROVIDER);

// Audit action types
export const AUDIT_ACTION = {
    // User actions
    USER_REGISTER: 'USER_REGISTER',
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_UPDATE: 'USER_UPDATE',
    USER_SUSPEND: 'USER_SUSPEND',
    USER_ACTIVATE: 'USER_ACTIVATE',
    USER_DELETE: 'USER_DELETE',

    // Seller actions
    SELLER_REGISTER: 'SELLER_REGISTER',
    SELLER_UPDATE: 'SELLER_UPDATE',
    SELLER_APPROVE: 'SELLER_APPROVE',
    SELLER_REJECT: 'SELLER_REJECT',
    SELLER_SUSPEND: 'SELLER_SUSPEND',
    SELLER_ACTIVATE: 'SELLER_ACTIVATE',
    SELLER_VERIFICATION_SUBMIT: 'SELLER_VERIFICATION_SUBMIT',

    // Store actions
    STORE_CREATE: 'STORE_CREATE',
    STORE_UPDATE: 'STORE_UPDATE',
    STORE_SUSPEND: 'STORE_SUSPEND',
    STORE_ACTIVATE: 'STORE_ACTIVATE',
    STORE_CLOSE: 'STORE_CLOSE',

    // Product actions
    PRODUCT_CREATE: 'PRODUCT_CREATE',
    PRODUCT_UPDATE: 'PRODUCT_UPDATE',
    PRODUCT_DELETE: 'PRODUCT_DELETE',
    PRODUCT_PUBLISH: 'PRODUCT_PUBLISH',
    PRODUCT_ARCHIVE: 'PRODUCT_ARCHIVE',

    // Inventory actions
    INVENTORY_UPDATE: 'INVENTORY_UPDATE',
    INVENTORY_LOW_STOCK: 'INVENTORY_LOW_STOCK',

    // Cart actions
    CART_ADD_ITEM: 'CART_ADD_ITEM',
    CART_UPDATE_ITEM: 'CART_UPDATE_ITEM',
    CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
    CART_CLEAR: 'CART_CLEAR',

    // Order actions
    ORDER_CREATE: 'ORDER_CREATE',
    ORDER_STATUS_CHANGE: 'ORDER_STATUS_CHANGE',
    ORDER_CANCEL: 'ORDER_CANCEL',
    ORDER_REFUND: 'ORDER_REFUND',

    // Payment actions
    PAYMENT_INITIATE: 'PAYMENT_INITIATE',
    PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
    PAYMENT_FAIL: 'PAYMENT_FAIL',
    PAYMENT_REFUND: 'PAYMENT_REFUND',

    // Admin actions
    ADMIN_CONFIG_UPDATE: 'ADMIN_CONFIG_UPDATE',
    ADMIN_CATEGORY_CREATE: 'ADMIN_CATEGORY_CREATE',
    ADMIN_CATEGORY_UPDATE: 'ADMIN_CATEGORY_UPDATE',
    ADMIN_CATEGORY_DELETE: 'ADMIN_CATEGORY_DELETE',
};

export const AUDIT_ACTION_VALUES = Object.values(AUDIT_ACTION);

// Pagination defaults
export const PAGINATION = {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 10,
    MAX_LIMIT: 100,
};

// Token expiry times
export const TOKEN_EXPIRY = {
    ACCESS_TOKEN: '15m',
    REFRESH_TOKEN: '7d',
    REFRESH_TOKEN_MS: 7 * 24 * 60 * 60 * 1000, // 7 days in milliseconds
};

export default {
    ACCOUNT_STATUS,
    SELLER_STATUS,
    STORE_STATUS,
    PRODUCT_STATUS,
    PAYMENT_STATUS,
    VERIFICATION_STATUS,
    DOCUMENT_TYPE,
    BUSINESS_TYPE,
    ADDRESS_TYPE,
    ADDRESS_LABEL,
    GENDER,
    AUTH_PROVIDER,
    AUDIT_ACTION,
    PAGINATION,
    TOKEN_EXPIRY,
};
